manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: ozalexo
      url-base: https://github.com/ozalexo
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: zmk-keyboard-dao
      remote: ozalexo
      revision: main
  self:
    path: config
